version: "3.9"
services:
  postgresql:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sup3R_Usr
      - POSTGRES_PASSWORD=th3DevP@ss
      - POSTGRES_DB=pgoi
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend
